#!/bin/bash

echo "==============================================="
echo "Encoder Fix Verification Test"
echo "==============================================="
echo ""
echo "This test verifies that the rotary encoder:"
echo "1. Changes algorithms without jumping back to CSAW"
echo "2. Properly syncs with host parameter changes"
echo "3. Maintains the selected algorithm after stopping rotation"
echo ""
echo "TEST PROCEDURE:"
echo "---------------"
echo "1. Open the standalone app or AU plugin in Logic"
echo "2. Rotate the encoder to select different algorithms"
echo "3. Stop on any algorithm (e.g., SNAR, BELL, DIGI)"
echo "4. Verify it STAYS on that algorithm (doesn't jump to CSAW)"
echo "5. In Logic: Change algorithm via dropdown"
echo "6. Verify the plugin UI updates to match"
echo "7. Rotate encoder again and verify it works from the new position"
echo ""
echo "EXPECTED RESULTS:"
echo "-----------------"
echo "✅ Encoder rotation changes algorithms smoothly"
echo "✅ Selected algorithm persists after stopping rotation"
echo "✅ NO jumping back to CSAW"
echo "✅ Bidirectional sync with Logic's parameter dropdown"
echo "✅ All 47 algorithms accessible via encoder"
echo ""
echo "CRITICAL FIX IMPLEMENTED:"
echo "-------------------------"
echo "- Fixed parameter value reading (was incorrectly treating index as normalized)"
echo "- Added feedback loop prevention flag"
echo "- Proper detection of encoder manipulation state"
echo ""
echo "Opening standalone app for testing..."
open build/Braidy_artefacts/Debug/Standalone/Braidy.app

echo ""
echo "Test started. Please perform the verification steps above."